// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valentine.Persistence;

namespace Valentine.Persistence.Migrations
{
    [DbContext(typeof(ValentineDbContext))]
    [Migration("20200213213901_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Valentine.Domain.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Valentine.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Valentine.Domain.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Valentine.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Valentine.Domain.Area", b =>
                {
                    b.HasOne("Valentine.Domain.Map", null)
                        .WithMany("Areas")
                        .HasForeignKey("MapId");
                });

            modelBuilder.Entity("Valentine.Domain.Image", b =>
                {
                    b.HasOne("Valentine.Domain.Area", null)
                        .WithMany("Images")
                        .HasForeignKey("AreaId");
                });

            modelBuilder.Entity("Valentine.Domain.User", b =>
                {
                    b.HasOne("Valentine.Domain.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");
                });
#pragma warning restore 612, 618
        }
    }
}
